### ISSUE TITLE
Badge field being `*int` breaks int assignment in go1.4

### ISSUE THREAD

**Issue by chakrit** [timehop/apns#18]
This line: https://github.com/timehop/apns/blob/master/notification.go#L50

Since it is a `*int` you can no longer assign `int` to it directly. This is probably due to the pointer handling changes in the recently released go1.4.

I think the docs needs updating to reflect this.

**Comment by nathany** [comment]
The example was updated in 4274e69b3a28afa3f7627f58f08619729bf82278 but the README still needs updating.

**Comment by chakrit** [comment]
I can help over the weekends if I dont forget it by then :p
