### ISSUE TITLE
Additional maintainers?

### ISSUE THREAD

**Issue by nathany** [timehop/apns#23]
@bdotdub Would it be possible to add some additional maintainers to this project?

#14 Has been open since December 10th. It has tests, it received code review and updates based on review. While it changes behaviour in certain instances, I don't think it would be considered a breaking change.

It's difficult to contribute further while these pull requests remain open.

**Comment by bdotdub** [comment]
Apologies on this. Just merge #14. I've got some time carved out this week to finish up the synchronous API. I'd like to get that out first and then started adding other maintainers. That sound cool for you?

**Comment by nathany** [comment]
Certainly. Thanks!

**Comment by bdotdub** [comment]
Revisiting this.

I've been overwhelmed with the non-code stuff here at timehop so I'd love to not let this repo stagnate. Adding @nathany as a maintainer. @tylrtrmbl - you as well?

**Comment by nathany** [comment]
Thanks @bdotdub.

**Comment by tylrtrmbl** [comment]
I'm happy being a guiding voice for now. Thank you @nathany and @bdotdub!

**Comment by nathany** [comment]
Thanks @tylrtrmbl.
