### ISSUE TITLE
Move away from pointers for badge field?

### ISSUE THREAD

**Issue by nathany** [timehop/apns#38]
> The only problem with using a series of pointers in structs is they can end in race conditions if any goroutines mutate the underlying pointer.

> For that reason, I took the same approach here for `omitempty` badges: https://github.com/joekarl/go-libapns/pull/8

> It's not "pretty" but it's thread-safe. @themartorana

**Comment by nathany** [comment]
This would be similar to the [NullInt64](http://golang.org/pkg/database/sql/#NullInt64) type in the sql package. :+1:

**Comment by tylrtrmbl** [comment]
:+1:

**Comment by nathany** [comment]
Before the PR from @themartorana, go-libapns was just using -1 to reset the badge rather than 0 (which is omitted, meaning no change).

anachronistic/apns uses an interface for different types of Alerts. That could be another option for the badge.

**Comment by themartorana** [comment]
The biggest issue I had with -1 is that the struct is initialized with 0, a valid (and badge-clearing) value. So unless you hide the struct but give it a public initializer method, its default state is to clear the badge.

**Comment by themartorana** [comment]
Ping on this - looks like we're still using a pointer. I can quickly submit a NullInt64-esque solution like https://github.com/joekarl/go-libapns/pull/8 (my preferred method). Thoughts?

**Comment by tylrtrmbl** [comment]
Go for it!

**Comment by nathany** [comment]
closed with #60
