### ISSUE TITLE
Connection Ideas

### ISSUE THREAD

**Issue by tylrtrmbl** [timehop/apns#49]
Hi all,

I've shared these ideas with @bdotdub and gone over parts with @nathany now as well. I just found my notes and figured I'd type them here on GitHub as well.

The ideas I will lay out below was guided by some factors from the community:
- We've seen some demand for a more mockable components, especially connections
- We've seen some demand for greater configuration of the connection
  - Example: Support connection-level Nagle's algorithm
  - Example: Support custom TLS configuration

Here's what I came up with:

The current `Connection` struct in `master` is simply a `net.Conn` wrapper with some configuration. This isn't the same as a mockable interface, and is probably insufficient. In `develop`, `Connection` handles three things:
- Read, write, and close (via `io.ReadWriteCloser`)
- Reconnection
- One configuration parameter: read deadline

I posit that if we move the responsibility for reconnection into the `Client`, we can get rid of the `Connection` altogether and simply use `io.ReadWriteCloser`. It would work this way:
- When the `Client` detects a connection (`io.ReadWriteCloser`) has gone sour, it gets a new one from a provider function
- We supply a default provider function that makes a connection configured with sensible defaults for a given gateway and `tls.Certificate`
#### Example

``` go

type ConnectionProvider func(gateway string, cert tls.Certificate) (io.ReadWriteCloser, error)

type Client struct {
    ...
    Gateway       string
    Cert          tls.Certificate
    NewConnection ConnectionProvider
    ...
}

func DefaultConnectionProvider(gateway string, cert tls.Certificate) (tls.Conn, err Error) {
    gatewayParts := strings.Split(gw, ":")
    config := tls.Config{
        Certificates:       []tls.Certificate{cert},
        ServerName:         gatewayParts[0],
    }

    return tls.Dial("tcp", gateway, config)
}

func NewClient(gateway, cert tls.Config) *Client{
    return &Client{
        Gateway: gateway,
        Cert: cert,
        NewConnection: DefaultConnectionProvider,
    }
}

func Example() {
    cert, err := tls.LoadX509KeyPair(certFile, keyFile)
    if err != nil {
        panic("cannot load APNS cert")
    }

    client := NewClient(ProductionGateway, cert)
    ...
}
```

With this scheme, the Client is able to make a new connection whenever it needs one. The user is able to replace `NewConnection` to provide a custom-configured connection, as well as replace `NewConnection` to provide a mock connection. `DefaultConnectionProvider` is exported so it can be used if the user wants override only a few settings from the default connection.

Let me know what you guys think!

**Comment by nathany** [comment]
What is an example of using a custom function? Say for #32 Nagel's algorithm.

I like the direction. Though I'm curious about the alternatives:
* a default/custom config vs. default/custom function
* a default dialer and custom dialer -- or rather, a custom function that returns a function that dials (without doing the config/setup each time).

I'd like to come up with a cleaner way to do gatewayParts before making this something people may need to write.
