### ISSUE TITLE
Failednotifs

### ISSUE THREAD

**Issue by pjebs** [timehop/apns#55]
When Failednotifs has objects, do I have to use the send command to attempt to resend?

**Comment by nathany** [comment]
timehop/apns automatically buffers the last 50 notifications and resends them if an error occurs (the notifications after the error)

**Comment by pjebs** [comment]
What if there were more than 50 notifications after the error occurred?
Are they lost forever?

**Comment by nathany** [comment]
At the moment, yes, it's a circular buffer so the most recent are kept. The code does continuously read off the socket for errors from Apple, so it should be more responsive than waiting for a write to fail.

Also, if the Go process you are running crashes, that buffer also disappears.

See #47 for some real world issues as of late.
